version: '2'  

services:  
  web:
    build: ./testapp
    container_name: flaskapp
    command: gunicorn --bind :8000 hello_world:create_app()
    expose:
      - "8000"
    
  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
    - web:web
  
